export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT_BY_ID  = "DELETE_CLIENT_BY_ID"; 
export const GET_CLIENTS = "GET_CLIENTS"; 
export const UPDATE_CLIENT_BY_ID = "UPDATE_CLIENT_BY_ID"; 
export const GET_CLIENT_BY_ID = "GET_CLIENT_BY_ID"; 