export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT_BY_ID  = "DELETE_CLIENT_BY_ID"; 
export const GET_CLIENTS = "GET_CLIENTS"; 
export const UPDATE_CLIENT_BY_ID = "UPDATE_CLIENT_BY_ID"; 
export const GET_CLIENT_BY_ID = "GET_CLIENT_BY_ID"; 


export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const USER_PROFILE = "USER_PROFILE"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"


